import { features } from './features/index.js';
import { load, save, clearFeature } from './store.js';
import { connectFirebase, syncFeature, syncAll, isConfigured } from './firebase-sync.js';

const $ = s => document.querySelector(s), app = $('#appMain');
let activeFeature = null, editingId = null;
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const date = () => new Date().toISOString().slice(0, 10), money = n => '₹' + Number(n || 0).toLocaleString('en-IN',{maximumFractionDigits:2}), uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
const dataFor = f => load(f.id, f.seed || []);
function toast(message){const e=$('#toast');e.textContent=message;e.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.classList.remove('show'),2500)}
function saveEntries(f, entries){save(f.id,entries);syncFeature(f.id,entries)}
function renderHome(){activeFeature=null;const runs=dataFor(features.find(f=>f.id==='run-walk'));const km=runs.filter(x=>x.date===date()).reduce((n,x)=>n+Number(x.km||0),0);app.innerHTML=`<section><div class="hero-card"><div><span>ಇಂದಿನ ಪ್ರಗತಿ</span><strong>${Math.min(100,Math.round(km/5*100))}%</strong><small>${km.toFixed(1)} / 5 KM</small></div><div class="ring" style="--p:${Math.min(100,km/5*100)}%"><b>${km.toFixed(1)}</b><small>KM</small></div></div><div class="section-head"><h2>Quick Actions</h2><small>${isConfigured()?'☁ Firebase sync on':'○ Local only'}</small></div><div class="quick-grid">${features.map(f=>`<button class="quick-button" data-open="${f.id}"><i>${f.icon}</i><span>${f.label}</span></button>`).join('')}</div><div class="sync-card"><b>☁ Firebase Backup</b><p>${isConfigured()?'ಹೊಸ ಎಂಟ್ರಿಗಳು Firebase ಗೆ backup ಆಗುತ್ತವೆ.':'Firebase ಇನ್ನೂ ಹೊಂದಿಸಿಲ್ಲ. README.md ನಲ್ಲಿ config ಸೇರಿಸಿ.'}</p>${isConfigured()?'<button class="text-button" data-sync>ಈಗ ಎಲ್ಲಾ backup ಮಾಡಿ</button>':''}</div></section>`}
function defaultList(entries,f){return entries.length?entries.slice().reverse().map(x=>`<article class="entry-card"><div><b>${esc(x.title||x.name||x.text||f.label)}</b><small>${esc(x.date||x.createdAt?.slice(0,10)||'')}</small>${x.amount!==undefined?`<strong>${money(x.amount)}</strong>`:''}${x.text?`<p>${esc(x.text)}</p>`:''}</div><div class="entry-actions"><button data-edit="${x.id}">✎</button><button data-delete="${x.id}">🗑</button></div></article>`).join(''):'<div class="empty">ಇನ್ನೂ ಯಾವುದೇ ಎಂಟ್ರಿ ಇಲ್ಲ.</div>'}
function renderFeature(f){activeFeature=f;const entries=dataFor(f),body=f.render?f.render(entries,{money,date,esc}):defaultList(entries,f);app.innerHTML=`<section class="feature-view"><header class="page-title"><div><span>${f.group}</span><h2>${f.icon} ${f.label}</h2></div><button class="add" data-add>＋</button></header>${body}<button class="back-wide" data-home>← Dashboard ಗೆ ಹಿಂತಿರುಗಿ</button></section>`}
function showForm(f,item=null){editingId=item?.id||null;$('#modalTitle').textContent=`${item?'ತಿದ್ದು':'ಸೇರಿಸಿ'} · ${f.label}`;$('#entryForm').innerHTML=f.fields.map(x=>`<label>${x.label}<input ${x.required===false?'':'required'} name="${x.key}" type="${x.type||'text'}" value="${esc(item?.[x.key]??x.value??'')}" placeholder="${x.placeholder||''}" ${x.step?`step="${x.step}"`:''}></label>`).join('')+'<button class="primary" type="submit">Save</button>';$('#entryModal').classList.add('open')}
function closeForm(){$('#entryModal').classList.remove('open')}
function handleSave(form){const values=Object.fromEntries(new FormData(form));const entries=dataFor(activeFeature),entry={...values,id:editingId||uid(),date:values.date||date(),createdAt:new Date().toISOString()};saveEntries(activeFeature,editingId?entries.map(x=>x.id===editingId?{...x,...entry}:x):[...entries,entry]);closeForm();renderFeature(activeFeature);toast(isConfigured()?'Firebase backup ಗೆ ಉಳಿಸಲಾಗಿದೆ':'ಈ device ನಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ')}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open)return renderFeature(features.find(f=>f.id===open.dataset.open));if(e.target.closest('[data-home]'))return renderHome();if(e.target.closest('[data-back]'))return activeFeature?renderHome():history.back();if(e.target.closest('[data-add]'))return showForm(activeFeature);if(e.target.closest('[data-close]'))return closeForm();if(e.target.closest('[data-sync]'))return syncAll(Object.fromEntries(features.map(f=>[f.id,dataFor(f)]))).then(()=>toast('ಎಲ್ಲಾ data Firebase ಗೆ backup ಆಯಿತು')).catch(()=>toast('Firebase backup ಆಗಲಿಲ್ಲ'));const edit=e.target.closest('[data-edit]');if(edit)return showForm(activeFeature,dataFor(activeFeature).find(x=>x.id===edit.dataset.edit));const del=e.target.closest('[data-delete]');if(del&&confirm('ಈ ಎಂಟ್ರಿ ಅಳಿಸಬೇಕೇ?')){saveEntries(activeFeature,dataFor(activeFeature).filter(x=>x.id!==del.dataset.delete));renderFeature(activeFeature)}});
$('#entryForm').addEventListener('submit',e=>{e.preventDefault();handleSave(e.currentTarget)});$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('life-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('life-theme')==='dark')document.body.classList.add('dark');connectFirebase().then(renderHome).catch(renderHome);
