(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const K={theme:'life_theme',runs:'runHistory',habits:'habitsList',payments:'emergencyCards',goals:'bucketList',notes:'notesHistory',diary:'diaryEntries',finance:'finance',tx:'transactions',start:'lifeStartDate',pinHash:'diaryPinHash'};
const TARGET=5;
const defaults=[['ನಲ್ಲಿಕಾಯಿ','🍈'],['Egg','🥚'],['Drink full water','💧'],['Eat before 8','🥗'],['Walk 30 minutes','🚶‍♂️']];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}; const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let runs=read(K.runs,[]), habits=read(K.habits,null), payments=read(K.payments,[]), goals=read(K.goals,[]), notes=read(K.notes,[]), diary=read(K.diary,[]), tx=read(K.tx,[]), finance=read(K.finance,{payable:'',receivable:''});
if(!habits) habits=defaults.map((x,i)=>({id:Date.now()+i,name:x[0],emoji:x[1],history:{}}));
if(!localStorage.getItem(K.start)) localStorage.setItem(K.start,new Date().toISOString().slice(0,10));
let diaryUnlocked=false, pendingPinMode='unlock';
const today=()=>new Date().toISOString().slice(0,10);
const money=n=>'₹'+(Number(n)||0).toLocaleString('en-IN',{maximumFractionDigits:2});
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove('show'),2200)}
function escape(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function nav(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));window.scrollTo({top:0,behavior:'smooth'})}
function openSheet(id){closeAll();$('#backdrop').classList.add('open');$('#'+id).classList.add('open')}
function closeAll(){ $$('.sheet').forEach(x=>x.classList.remove('open'));$('#backdrop').classList.remove('open') }
function renderRuns(){const d=today();const km=runs.filter(x=>x.date===d).reduce((a,x)=>a+Number(x.km||0),0);const pct=Math.min(100,km/TARGET*100);$('#homeKm').textContent=km.toFixed(1);$('#activityKm').textContent=km.toFixed(1);$('#homeProgress').textContent=Math.round(pct)+'%';$('#homeProgressText').textContent=km>=TARGET?'ಇಂದಿನ ಗುರಿ ಮುಗಿದಿದೆ 🎉':`${(TARGET-km).toFixed(1)} KM ಇನ್ನೂ ಬಾಕಿ`;$('#homeRing').style.setProperty('--p',pct+'%');$('#activityBar').style.width=pct+'%';$('#runHistoryList').innerHTML=runs.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10).map(x=>`<div class="list-row"><span>🏃</span><div class="grow"><strong>${escape(x.date)}</strong><small>Run / Walk</small></div><b>${Number(x.km).toFixed(1)} KM</b></div>`).join('')||'<div class="list-row"><small>No run history yet.</small></div>'}
function renderHabits(){const d=today();const html=habits.map(h=>{const done=h.history?.[d]==='done';return `<div class="list-row"><button class="check ${done?'done':''}" data-habit="${h.id}">${done?'✓':'○'}</button><div class="grow"><strong>${escape(h.emoji||'✓')} ${escape(h.name)}</strong><small>${done?'Completed today':'Tap to complete'}</small></div><button data-edit-habit="${h.id}">⋯</button></div>`}).join('');$('#homeHabits').innerHTML=habits.slice(0,4).map(h=>{const done=h.history?.[d]==='done';return `<div class="list-row"><button class="check ${done?'done':''}" data-habit="${h.id}">${done?'✓':'○'}</button><div class="grow"><strong>${escape(h.emoji||'✓')} ${escape(h.name)}</strong><small>${done?'Done':'Tap to complete'}</small></div></div>`}).join('')||'<div class="list-row"><small>Add your first habit.</small></div>';$('#allHabits').innerHTML=html||'<div class="list-row"><small>No habits yet.</small></div>'}
function renderPayments(){const html=payments.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||'')).map(p=>`<div class="list-row"><span>${p.type==='receivable'?'💚':'💳'}</span><div class="grow"><strong>${escape(p.title)}</strong><small>${p.date||'No date'} · ${p.type==='receivable'?'Receivable':'Payable'}</small></div><b class="amount ${p.type==='receivable'?'income':'expense'}">${money(p.amount)}</b></div>`).join('');$('#homePayments').innerHTML=html||'<div class="list-row"><small>No upcoming payments.</small></div>'}
function renderFinance(){let pay=Number(finance.payable)||0,rec=Number(finance.receivable)||0;payments.forEach(p=>p.type==='payable'?pay+=Number(p.amount)||0:rec+=Number(p.amount)||0);$('#homePayable').textContent=money(pay);$('#homeReceivable').textContent=money(rec);$('#moneyPayable').textContent=money(pay);$('#moneyReceivable').textContent=money(rec);$('#netBalance').textContent=money(rec-pay);$('#payableInput').value=finance.payable||'';$('#receivableInput').value=finance.receivable||'';$('#transactionsList').innerHTML=tx.slice().reverse().map(x=>`<div class="list-row transaction"><div class="grow"><strong>${escape(x.title)}</strong><small>${escape(x.date)}</small></div><b class="amount ${x.type}">${x.type==='income'?'+':'-'}${money(x.amount)}</b></div>`).join('')||'<div class="list-row"><small>No transactions yet.</small></div>'}
function renderGoals(){$('#goalsList').innerHTML=goals.map(g=>`<div class="list-row"><span>🎯</span><div class="grow"><strong>${escape(g.title)}</strong><small>Target ${money(g.budget||0)}</small></div><button data-delete-goal="${g.id}">🗑</button></div>`).join('')||'<div class="list-row"><small>No goals yet.</small></div>'}
function renderDiary(){if(!diaryUnlocked)return;$('#diaryHistory').innerHTML=diary.slice().reverse().map(x=>`<div class="list-row"><div class="grow"><strong>${escape(x.date)}</strong><small>${escape(x.text)}</small></div></div>`).join('')||'<div class="list-row"><small>No entries yet.</small></div>'}
function refresh(){renderRuns();renderHabits();renderPayments();renderFinance();renderGoals();renderDiary()}
async function hashPin(pin){const data=new TextEncoder().encode(pin);const b=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function openPin(mode){pendingPinMode=mode;$('#pinTitle').textContent=mode==='setup'?'Set Diary PIN':'Unlock Diary';$('#pinHint').textContent=mode==='setup'?'Choose a PIN. It is stored as a hash on this device.':'Enter your Diary PIN.';$('#pinInput').value='';$('#pinModal').classList.add('open');setTimeout(()=>$('#pinInput').focus(),100)}
async function submitPin(){const pin=$('#pinInput').value.trim();if(pin.length<4)return toast('ಕನಿಷ್ಠ 4 digit PIN ಬೇಕು');const h=await hashPin(pin);if(pendingPinMode==='setup'){localStorage.setItem(K.pinHash,h);diaryUnlocked=true;$('#diaryLocked').hidden=true;$('#diaryOpen').hidden=false;$('#pinModal').classList.remove('open');renderDiary();toast('Diary PIN set ಆಯಿತು')}else if(h===localStorage.getItem(K.pinHash)){diaryUnlocked=true;$('#diaryLocked').hidden=true;$('#diaryOpen').hidden=false;$('#pinModal').classList.remove('open');renderDiary();toast('Diary unlocked')}else toast('Wrong PIN')}
function exportData(){const data={version:2,runs,habits,payments,goals,notes,diary,finance,tx,startDate:localStorage.getItem(K.start),theme:localStorage.getItem(K.theme)};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='life-app-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded')}
function importData(){ $('#restoreInput').click() }
$('#restoreInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);runs=d.runs||[];habits=d.habits||habits;payments=d.payments||[];goals=d.goals||[];notes=d.notes||[];diary=d.diary||[];finance=d.finance||{};tx=d.tx||[];write(K.runs,runs);write(K.habits,habits);write(K.payments,payments);write(K.goals,goals);write(K.notes,notes);write(K.diary,diary);write(K.finance,finance);write(K.tx,tx);if(d.startDate)localStorage.setItem(K.start,d.startDate);if(d.theme)localStorage.setItem(K.theme,d.theme);applyTheme();refresh();toast('Restore complete')}catch{toast('Invalid backup file')}};r.readAsText(f);e.target.value=''})
$('#backdrop').onclick=closeAll;
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
$$('[data-sheet]').forEach(b=>b.addEventListener('click',()=>openSheet(b.dataset.sheet)));
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>actions(b.dataset.action)));
$('#themeToggle').onclick=()=>{localStorage.setItem(K.theme,document.body.classList.contains('dark')?'light':'dark');applyTheme()};
function applyTheme(){const dark=localStorage.getItem(K.theme)==='dark';document.body.classList.toggle('dark',dark);$('#themeToggle').textContent=dark?'☀':'☾'}
function actions(a){if(a==='closeModal'){$$('.modal').forEach(x=>x.classList.remove('open'));return}if(a==='saveRun'){const n=Number($('#runInput').value);if(!n||n<0)return toast('KM ನಮೂದಿಸಿ');runs.push({date:today(),km:n});write(K.runs,runs);$('#runInput').value='';closeAll();refresh();toast('Run added ✓')}else if(a==='saveHabit'){const name=$('#habitName').value.trim();if(!name)return toast('Habit name ಬೇಕು');habits.push({id:Date.now(),name,emoji:$('#habitEmoji').value.trim()||'✓',history:{}});write(K.habits,habits);$('#habitName').value='';$('#habitEmoji').value='';closeAll();refresh();toast('Habit added')}else if(a==='savePayment'){const title=$('#paymentTitle').value.trim(),amount=Number($('#paymentAmount').value);if(!title||!amount)return toast('Title ಮತ್ತು amount ಬೇಕು');payments.push({id:Date.now(),title,amount,type:$('#paymentType').value,date:$('#paymentDate').value||today()});write(K.payments,payments);$('#paymentTitle').value='';$('#paymentAmount').value='';closeAll();refresh();toast('Payment saved')}else if(a==='saveTransaction'){const title=$('#txTitle').value.trim(),amount=Number($('#txAmount').value);if(!title||!amount)return toast('Details ಬೇಕು');tx.push({id:Date.now(),title,amount,type:$('#txType').value,date:today()});write(K.tx,tx);$('#txTitle').value='';$('#txAmount').value='';closeAll();refresh();toast('Transaction added')}else if(a==='saveGoal'){const title=$('#goalTitle').value.trim();if(!title)return toast('Goal name ಬೇಕು');goals.push({id:Date.now(),title,budget:Number($('#goalBudget').value)||0});write(K.goals,goals);$('#goalTitle').value='';$('#goalBudget').value='';closeAll();refresh();toast('Goal added')}else if(a==='saveNote'){const text=$('#noteText').value.trim();if(!text)return toast('Note ಬರೆಯಿರಿ');notes.push({date:today(),text});write(K.notes,notes);$('#noteText').value='';closeAll();toast('Note saved')}else if(a==='unlockDiary'){openPin(localStorage.getItem(K.pinHash)?'unlock':'setup')}else if(a==='submitPin')submitPin();else if(a==='lockDiary'){diaryUnlocked=false;$('#diaryOpen').hidden=true;$('#diaryLocked').hidden=false;toast('Diary locked')}else if(a==='saveDiary'){const text=$('#diaryText').value.trim();if(!text)return toast('Entry ಬರೆಯಿರಿ');diary.push({date:new Date().toLocaleString('en-IN'),text});write(K.diary,diary);$('#diaryText').value='';renderDiary();toast('Diary entry saved')}else if(a==='exportData')exportData();else if(a==='importData')importData();else if(a==='showAbout')$('#aboutModal').classList.add('open');else if(a==='showNotes')alert(notes.map(n=>`${n.date}: ${n.text}`).join('\n\n')||'No notes yet')}
$$('[data-habit]').forEach(()=>{});document.addEventListener('click',e=>{const h=e.target.closest('[data-habit]');if(h){const item=habits.find(x=>String(x.id)===h.dataset.habit);if(item){const d=today();item.history=item.history||{};item.history[d]=item.history[d]==='done'?'':'done';write(K.habits,habits);refresh();toast(item.history[d]==='done'?'Habit complete ✓':'Habit undone')}}const del=e.target.closest('[data-delete-goal]');if(del){goals=goals.filter(g=>String(g.id)!==del.dataset.deleteGoal);write(K.goals,goals);refresh();toast('Goal deleted')}});
$('#saveFinance').onclick=()=>{finance={payable:$('#payableInput').value,receivable:$('#receivableInput').value};write(K.finance,finance);refresh();toast('Finance snapshot saved')};$('#saveDiary').onclick=()=>actions('saveDiary');
$('#greeting').textContent=(new Date().getHours()<12?'ಶುಭೋದಯ':'ನಮಸ್ಕಾರ')+' 👋';applyTheme();refresh();
})();
